In [1]:
import polars as pl

In [ ]:
df = pl.read_csv('scraping/assets/dogs_cleaned_with_descriptions.csv')

In [5]:
for link in df["Detailed Description Link"]:
    print(link)

https://dogtime.com/dog-breeds/afador
https://dogtime.com/dog-breeds/affenhuahua
https://dogtime.com/dog-breeds/affenpinscher
https://dogtime.com/dog-breeds/afghan-hound
https://dogtime.com/dog-breeds/airedale-terrier
https://dogtime.com/dog-breeds/akbash
https://dogtime.com/dog-breeds/akita
https://dogtime.com/dog-breeds/akita-chow
https://dogtime.com/dog-breeds/akita-pit
https://dogtime.com/dog-breeds/akita-shepherd
https://dogtime.com/dog-breeds/alaskan-klee-kai
https://dogtime.com/dog-breeds/alaskan-malamute
https://dogtime.com/dog-breeds/american-bulldog
https://dogtime.com/dog-breeds/american-english-coonhound
https://dogtime.com/dog-breeds/american-eskimo-dog
https://dogtime.com/dog-breeds/american-foxhound
https://dogtime.com/dog-breeds/american-hairless-terrier
https://dogtime.com/dog-breeds/american-leopard-hound
https://dogtime.com/dog-breeds/american-pit-bull-terrier
https://dogtime.com/dog-breeds/american-pugabull
https://dogtime.com/dog-breeds/american-staffordshire-terrier
https://dogtime.com/dog-breeds/american-water-spaniel
https://dogtime.com/dog-breeds/anatolian-shepherd-dog
https://dogtime.com/dog-breeds/appenzeller-sennenhunde
https://dogtime.com/dog-breeds/auggie
https://dogtime.com/dog-breeds/aussiedoodle
https://dogtime.com/dog-breeds/aussiepom
https://dogtime.com/dog-breeds/australian-cattle-dog
https://dogtime.com/dog-breeds/australian-kelpie
https://dogtime.com/dog-breeds/australian-retriever
https://dogtime.com/dog-breeds/australian-shepherd
https://dogtime.com/dog-breeds/australian-shepherd-husky
https://dogtime.com/dog-breeds/australian-shepherd-lab-mix
https://dogtime.com/dog-breeds/australian-shepherd-pit-bull-mix
https://dogtime.com/dog-breeds/australian-stumpy-tail-cattle-dog
https://dogtime.com/dog-breeds/australian-terrier
https://dogtime.com/dog-breeds/azawakh
https://dogtime.com/dog-breeds/barbet
https://dogtime.com/dog-breeds/basenji
https://dogtime.com/dog-breeds/bassador
https://dogtime.com/dog-breeds/basset-fauve-de-bretagne
https://dogtime.com/dog-breeds/basset-hound
https://dogtime.com/dog-breeds/basset-retriever
https://dogtime.com/dog-breeds/bavarian-mountain-scent-hound
https://dogtime.com/dog-breeds/beabull
https://dogtime.com/dog-breeds/beagle
https://dogtime.com/dog-breeds/beaglier
https://dogtime.com/dog-breeds/bearded-collie
https://dogtime.com/dog-breeds/bedlington-terrier
https://dogtime.com/dog-breeds/belgian-laekenois
https://dogtime.com/dog-breeds/belgian-malinois
https://dogtime.com/dog-breeds/belgian-sheepdog
https://dogtime.com/dog-breeds/belgian-tervuren
https://dogtime.com/dog-breeds/bergamasco-sheepdog
https://dogtime.com/dog-breeds/berger-picard
https://dogtime.com/dog-breeds/bernedoodle
https://dogtime.com/dog-breeds/bernese-mountain-dog
https://dogtime.com/dog-breeds/bichon-frise
https://dogtime.com/dog-breeds/biewer-terrier
https://dogtime.com/dog-breeds/black-and-tan-coonhound
https://dogtime.com/dog-breeds/black-mouth-cur
https://dogtime.com/dog-breeds/black-russian-terrier
https://dogtime.com/dog-breeds/bloodhound
https://dogtime.com/dog-breeds/blue-lacy
https://dogtime.com/dog-breeds/bluetick-coonhound
https://dogtime.com/dog-breeds/bocker
https://dogtime.com/dog-breeds/boerboel
https://dogtime.com/dog-breeds/boglen-terrier
https://dogtime.com/dog-breeds/bohemian-shepherd
https://dogtime.com/dog-breeds/bolognese
https://dogtime.com/dog-breeds/borador
https://dogtime.com/dog-breeds/border-collie
https://dogtime.com/dog-breeds/border-sheepdog
https://dogtime.com/dog-breeds/border-terrier
https://dogtime.com/dog-breeds/bordoodle
https://dogtime.com/dog-breeds/borzoi
https://dogtime.com/dog-breeds/boshih
https://dogtime.com/dog-breeds/bossie
https://dogtime.com/dog-breeds/boston-boxer
https://dogtime.com/dog-breeds/boston-terrier
https://dogtime.com/dog-breeds/boston-terrier-pekingese-mix
https://dogtime.com/dog-breeds/bouvier-des-flandres
https://dogtime.com/dog-breeds/boxador
https://dogtime.com/dog-breeds/boxer
https://dogtime.com/dog-breeds/boxerdoodle
https://dogtime.com/dog-breeds/boxmatian
https://dogtime.com/dog-breeds/boxweiler
https://dogtime.com/dog-breeds/boykin-spaniel
https://dogtime.com/dog-breeds/bracco-italiano
https://dogtime.com/dog-breeds/braque-du-bourbonnais
https://dogtime.com/dog-breeds/briard
https://dogtime.com/dog-breeds/brittany
https://dogtime.com/dog-breeds/broholmer
https://dogtime.com/dog-breeds/brussels-griffon
https://dogtime.com/dog-breeds/bugg
https://dogtime.com/dog-breeds/bull-arab
https://dogtime.com/dog-breeds/bull-pei
https://dogtime.com/dog-breeds/bull-terrier
https://dogtime.com/dog-breeds/bullador
https://dogtime.com/dog-breeds/bullboxer-pit
https://dogtime.com/dog-breeds/bulldog
https://dogtime.com/dog-breeds/bullmastiff
https://dogtime.com/dog-breeds/bullmatian
https://dogtime.com/dog-breeds/cairn-terrier
https://dogtime.com/dog-breeds/canaan-dog
https://dogtime.com/dog-breeds/cane-corso
https://dogtime.com/dog-breeds/cardigan-welsh-corgi
https://dogtime.com/dog-breeds/carolina-dog
https://dogtime.com/dog-breeds/catahoula-bulldog
https://dogtime.com/dog-breeds/catahoula-leopard-dog
https://dogtime.com/dog-breeds/caucasian-shepherd-dog
https://dogtime.com/dog-breeds/cav-a-jack
https://dogtime.com/dog-breeds/cavachon
https://dogtime.com/dog-breeds/cavador
https://dogtime.com/dog-breeds/cavalier-king-charles-spaniel
https://dogtime.com/dog-breeds/cavapoo
https://dogtime.com/dog-breeds/central-asian-shepherd-dog
https://dogtime.com/dog-breeds/cesky-terrier
https://dogtime.com/dog-breeds/chabrador
https://dogtime.com/dog-breeds/cheagle
https://dogtime.com/dog-breeds/chesapeake-bay-retriever
https://dogtime.com/dog-breeds/chi-chi
https://dogtime.com/dog-breeds/chi-poo
https://dogtime.com/dog-breeds/chigi
https://dogtime.com/dog-breeds/chihuahua
https://dogtime.com/dog-breeds/chilier
https://dogtime.com/dog-breeds/chinese-crested
https://dogtime.com/dog-breeds/chinese-shar-pei
https://dogtime.com/dog-breeds/chinook
https://dogtime.com/dog-breeds/chion
https://dogtime.com/dog-breeds/chipin
https://dogtime.com/dog-breeds/chiweenie
https://dogtime.com/dog-breeds/chorkie
https://dogtime.com/dog-breeds/chow-chow
https://dogtime.com/dog-breeds/chow-shepherd
https://dogtime.com/dog-breeds/chug
https://dogtime.com/dog-breeds/chusky
https://dogtime.com/dog-breeds/cirneco-delletna
https://dogtime.com/dog-breeds/clumber-spaniel
https://dogtime.com/dog-breeds/cockalier
https://dogtime.com/dog-breeds/cockapoo
https://dogtime.com/dog-breeds/cocker-spaniel
https://dogtime.com/dog-breeds/collie
https://dogtime.com/dog-breeds/corgi-inu
https://dogtime.com/dog-breeds/corgidor
https://dogtime.com/dog-breeds/corman-shepherd
https://dogtime.com/dog-breeds/coton-de-tulear
https://dogtime.com/dog-breeds/croatian-sheepdog
https://dogtime.com/dog-breeds/curly-coated-retriever
https://dogtime.com/dog-breeds/dachsador
https://dogtime.com/dog-breeds/dachshund
https://dogtime.com/dog-breeds/dalmatian
https://dogtime.com/dog-breeds/dandie-dinmont-terrier
https://dogtime.com/dog-breeds/daniff
https://dogtime.com/dog-breeds/danish-swedish-farmdog
https://dogtime.com/dog-breeds/deutscher-wachtelhund
https://dogtime.com/dog-breeds/doberdor
https://dogtime.com/dog-breeds/doberman-pinscher
https://dogtime.com/dog-breeds/docker
https://dogtime.com/dog-breeds/dogo-argentino
https://dogtime.com/dog-breeds/dogue-de-bordeaux
https://dogtime.com/dog-breeds/dorgi
https://dogtime.com/dog-breeds/dorkie
https://dogtime.com/dog-breeds/doxiepoo
https://dogtime.com/dog-breeds/doxle
https://dogtime.com/dog-breeds/drentsche-patrijshond
https://dogtime.com/dog-breeds/drever
https://dogtime.com/dog-breeds/dutch-shepherd
https://dogtime.com/dog-breeds/english-cocker-spaniel
https://dogtime.com/dog-breeds/english-foxhound
https://dogtime.com/dog-breeds/english-setter
https://dogtime.com/dog-breeds/english-springer-spaniel
https://dogtime.com/dog-breeds/english-toy-spaniel
https://dogtime.com/dog-breeds/entlebucher-mountain-dog
https://dogtime.com/dog-breeds/estrela-mountain-dog
https://dogtime.com/dog-breeds/eurasier
https://dogtime.com/dog-breeds/field-spaniel
https://dogtime.com/dog-breeds/fila-brasileiro
https://dogtime.com/dog-breeds/finnish-lapphund
https://dogtime.com/dog-breeds/finnish-spitz
https://dogtime.com/dog-breeds/flat-coated-retriever
https://dogtime.com/dog-breeds/fox-terrier
https://dogtime.com/dog-breeds/french-bulldog
https://dogtime.com/dog-breeds/french-bullhuahua
https://dogtime.com/dog-breeds/french-spaniel
https://dogtime.com/dog-breeds/frenchton
https://dogtime.com/dog-breeds/frengle
https://dogtime.com/dog-breeds/german-longhaired-pointer
https://dogtime.com/dog-breeds/german-pinscher
https://dogtime.com/dog-breeds/german-shepherd-dog
https://dogtime.com/dog-breeds/german-shepherd-pit-bull
https://dogtime.com/dog-breeds/german-shepherd-rottweiler-mix
https://dogtime.com/dog-breeds/german-sheprador
https://dogtime.com/dog-breeds/german-shorthaired-pointer
https://dogtime.com/dog-breeds/german-spitz
https://dogtime.com/dog-breeds/german-wirehaired-pointer
https://dogtime.com/dog-breeds/giant-schnauzer
https://dogtime.com/dog-breeds/glen-of-imaal-terrier
https://dogtime.com/dog-breeds/goberian
https://dogtime.com/dog-breeds/goldador
https://dogtime.com/dog-breeds/golden-cocker-retriever
https://dogtime.com/dog-breeds/golden-mountain-dog
https://dogtime.com/dog-breeds/golden-retriever
https://dogtime.com/dog-breeds/golden-retriever-corgi
https://dogtime.com/dog-breeds/golden-shepherd
https://dogtime.com/dog-breeds/goldendoodle
https://dogtime.com/dog-breeds/gollie
https://dogtime.com/dog-breeds/gordon-setter
https://dogtime.com/dog-breeds/great-dane
https://dogtime.com/dog-breeds/great-pyrenees
https://dogtime.com/dog-breeds/greater-swiss-mountain-dog
https://dogtime.com/dog-breeds/greyador
https://dogtime.com/dog-breeds/greyhound
https://dogtime.com/dog-breeds/hamiltonstovare
https://dogtime.com/dog-breeds/hanoverian-scenthound
https://dogtime.com/dog-breeds/harrier
https://dogtime.com/dog-breeds/havanese
https://dogtime.com/dog-breeds/havapoo
https://dogtime.com/dog-breeds/hokkaido
https://dogtime.com/dog-breeds/horgi
https://dogtime.com/dog-breeds/hovawart
https://dogtime.com/dog-breeds/huskita
https://dogtime.com/dog-breeds/huskydoodle
https://dogtime.com/dog-breeds/ibizan-hound
https://dogtime.com/dog-breeds/icelandic-sheepdog
https://dogtime.com/dog-breeds/irish-red-and-white-setter
https://dogtime.com/dog-breeds/irish-setter
https://dogtime.com/dog-breeds/irish-terrier
https://dogtime.com/dog-breeds/irish-water-spaniel
https://dogtime.com/dog-breeds/irish-wolfhound
https://dogtime.com/dog-breeds/italian-greyhound
https://dogtime.com/dog-breeds/jack-a-poo
https://dogtime.com/dog-breeds/jack-chi
https://dogtime.com/dog-breeds/jack-russell-terrier
https://dogtime.com/dog-breeds/jackshund
https://dogtime.com/dog-breeds/japanese-chin
https://dogtime.com/dog-breeds/japanese-spitz
https://dogtime.com/dog-breeds/jindo
https://dogtime.com/dog-breeds/kai-ken
https://dogtime.com/dog-breeds/karelian-bear-dog
https://dogtime.com/dog-breeds/keeshond
https://dogtime.com/dog-breeds/kerry-blue-terrier
https://dogtime.com/dog-breeds/king-shepherd
https://dogtime.com/dog-breeds/kishu-ken
https://dogtime.com/dog-breeds/komondor
https://dogtime.com/dog-breeds/kooikerhondje
https://dogtime.com/dog-breeds/kuvasz
https://dogtime.com/dog-breeds/kyi-leo
https://dogtime.com/dog-breeds/lab-pointer
https://dogtime.com/dog-breeds/labernese
https://dogtime.com/dog-breeds/labmaraner
https://dogtime.com/dog-breeds/labrabull
https://dogtime.com/dog-breeds/labradane
https://dogtime.com/dog-breeds/labradoodle
https://dogtime.com/dog-breeds/labrador-retriever
https://dogtime.com/dog-breeds/labrastaff
https://dogtime.com/dog-breeds/labsky
https://dogtime.com/dog-breeds/lagotto-romagnolo
https://dogtime.com/dog-breeds/lakeland-terrier
https://dogtime.com/dog-breeds/lancashire-heeler
https://dogtime.com/dog-breeds/leonberger
https://dogtime.com/dog-breeds/lhasa-apso
https://dogtime.com/dog-breeds/lhasapoo
https://dogtime.com/dog-breeds/lowchen
https://dogtime.com/dog-breeds/maltese
https://dogtime.com/dog-breeds/maltese-shih-tzu
https://dogtime.com/dog-breeds/maltipoo
https://dogtime.com/dog-breeds/manchester-terrier
https://dogtime.com/dog-breeds/maremma-sheepdog
https://dogtime.com/dog-breeds/mastador
https://dogtime.com/dog-breeds/mastiff
https://dogtime.com/dog-breeds/miniature-pinscher
https://dogtime.com/dog-breeds/miniature-schnauzer
https://dogtime.com/dog-breeds/morkie
https://dogtime.com/dog-breeds/mountain-cur
https://dogtime.com/dog-breeds/mountain-feist
https://dogtime.com/dog-breeds/mudi
https://dogtime.com/dog-breeds/neapolitan-mastiff
https://dogtime.com/dog-breeds/newfoundland
https://dogtime.com/dog-breeds/norfolk-terrier
https://dogtime.com/dog-breeds/northern-inuit-dog
https://dogtime.com/dog-breeds/norwegian-buhund
https://dogtime.com/dog-breeds/norwegian-elkhound
https://dogtime.com/dog-breeds/norwegian-lundehund
https://dogtime.com/dog-breeds/norwich-terrier
https://dogtime.com/dog-breeds/nova-scotia-duck-tolling-retriever
https://dogtime.com/dog-breeds/old-english-sheepdog
https://dogtime.com/dog-breeds/otterhound
https://dogtime.com/dog-breeds/papillon
https://dogtime.com/dog-breeds/papipoo
https://dogtime.com/dog-breeds/patterdale-terrier
https://dogtime.com/dog-breeds/peekapoo
https://dogtime.com/dog-breeds/pekingese
https://dogtime.com/dog-breeds/pembroke-welsh-corgi
https://dogtime.com/dog-breeds/petit-basset-griffon-vendeen
https://dogtime.com/dog-breeds/pharaoh-hound
https://dogtime.com/dog-breeds/pitsky
https://dogtime.com/dog-breeds/plott
https://dogtime.com/dog-breeds/pocket-beagle
https://dogtime.com/dog-breeds/pointer
https://dogtime.com/dog-breeds/polish-lowland-sheepdog
https://dogtime.com/dog-breeds/pomapoo
https://dogtime.com/dog-breeds/pomchi
https://dogtime.com/dog-breeds/pomeagle
https://dogtime.com/dog-breeds/pomeranian
https://dogtime.com/dog-breeds/pomsky
https://dogtime.com/dog-breeds/poochon
https://dogtime.com/dog-breeds/poodle
https://dogtime.com/dog-breeds/portuguese-podengo-pequeno
https://dogtime.com/dog-breeds/portuguese-pointer
https://dogtime.com/dog-breeds/portuguese-sheepdog
https://dogtime.com/dog-breeds/portuguese-water-dog
https://dogtime.com/dog-breeds/pudelpointer
https://dogtime.com/dog-breeds/pug
https://dogtime.com/dog-breeds/pugalier
https://dogtime.com/dog-breeds/puggle
https://dogtime.com/dog-breeds/puginese
https://dogtime.com/dog-breeds/puli
https://dogtime.com/dog-breeds/pyredoodle
https://dogtime.com/dog-breeds/pyrenean-mastiff
https://dogtime.com/dog-breeds/pyrenean-shepherd
https://dogtime.com/dog-breeds/rat-terrier
https://dogtime.com/dog-breeds/redbone-coonhound
https://dogtime.com/dog-breeds/rhodesian-ridgeback
https://dogtime.com/dog-breeds/rottador
https://dogtime.com/dog-breeds/rottle
https://dogtime.com/dog-breeds/rottweiler
https://dogtime.com/dog-breeds/saint-berdoodle
https://dogtime.com/dog-breeds/saint-bernard
https://dogtime.com/dog-breeds/saluki
https://dogtime.com/dog-breeds/samoyed
https://dogtime.com/dog-breeds/samusky
https://dogtime.com/dog-breeds/schipperke
https://dogtime.com/dog-breeds/schnoodle
https://dogtime.com/dog-breeds/scottish-deerhound
https://dogtime.com/dog-breeds/scottish-terrier
https://dogtime.com/dog-breeds/sealyham-terrier
https://dogtime.com/dog-breeds/sheepadoodle
https://dogtime.com/dog-breeds/shepsky
https://dogtime.com/dog-breeds/shetland-sheepdog
https://dogtime.com/dog-breeds/shiba-inu
https://dogtime.com/dog-breeds/shichon
https://dogtime.com/dog-breeds/shih-poo
https://dogtime.com/dog-breeds/shih-tzu
https://dogtime.com/dog-breeds/shikoku
https://dogtime.com/dog-breeds/shiloh-shepherd
https://dogtime.com/dog-breeds/shiranian
https://dogtime.com/dog-breeds/shollie
https://dogtime.com/dog-breeds/shorkie
https://dogtime.com/dog-breeds/siberian-husky
https://dogtime.com/dog-breeds/silken-windhound
https://dogtime.com/dog-breeds/silky-terrier
https://dogtime.com/dog-breeds/skye-terrier
https://dogtime.com/dog-breeds/sloughi
https://dogtime.com/dog-breeds/small-munsterlander-pointer
https://dogtime.com/dog-breeds/soft-coated-wheaten-terrier
https://dogtime.com/dog-breeds/spanish-mastiff
https://dogtime.com/dog-breeds/spinone-italiano
https://dogtime.com/dog-breeds/springador
https://dogtime.com/dog-breeds/stabyhoun
https://dogtime.com/dog-breeds/staffordshire-bull-terrier
https://dogtime.com/dog-breeds/staffy-bull-bullmastiff
https://dogtime.com/dog-breeds/standard-schnauzer
https://dogtime.com/dog-breeds/sussex-spaniel
https://dogtime.com/dog-breeds/swedish-lapphund
https://dogtime.com/dog-breeds/swedish-vallhund
https://dogtime.com/dog-breeds/taiwan-dog
https://dogtime.com/dog-breeds/terripoo
https://dogtime.com/dog-breeds/texas-heeler
https://dogtime.com/dog-breeds/thai-ridgeback
https://dogtime.com/dog-breeds/tibetan-mastiff
https://dogtime.com/dog-breeds/tibetan-spaniel
https://dogtime.com/dog-breeds/tibetan-terrier
https://dogtime.com/dog-breeds/toy-fox-terrier
https://dogtime.com/dog-breeds/transylvanian-hound
https://dogtime.com/dog-breeds/treeing-tennessee-brindle
https://dogtime.com/dog-breeds/treeing-walker-coonhound
https://dogtime.com/dog-breeds/valley-bulldog
https://dogtime.com/dog-breeds/vizsla
https://dogtime.com/dog-breeds/weimaraner
https://dogtime.com/dog-breeds/welsh-springer-spaniel
https://dogtime.com/dog-breeds/welsh-terrier
https://dogtime.com/dog-breeds/west-highland-white-terrier
https://dogtime.com/dog-breeds/westiepoo
https://dogtime.com/dog-breeds/whippet
https://dogtime.com/dog-breeds/whoodle
https://dogtime.com/dog-breeds/wirehaired-pointing-griffon
https://dogtime.com/dog-breeds/xoloitzuintli
https://dogtime.com/dog-breeds/yakutian-laika
https://dogtime.com/dog-breeds/yorkipoo
https://dogtime.com/dog-breeds/yorkshire-terrier

In [22]:
import requests
import time
from scrapy import Selector

CONTENT_DIV = "div.entry-content.wp-block-post-content"
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; dogbreed-scraper/1.0)"}

descriptions = []
links = df["Detailed Description Link"]
total = len(links)

for i, link in enumerate(links, start=1):
    try:
        response = requests.get(link, headers=HEADERS, timeout=10)
        response.raise_for_status()
        sel = Selector(text=response.text)
        paragraphs = [
            " ".join(p.css("::text").getall()).strip()
            for p in sel.css(f"{CONTENT_DIV} > p")
        ]
        description = " ".join(p for p in paragraphs if p)
    except Exception as e:
        print(f"[{i}/{total}] Failed {link}: {e}")
        description = None

    descriptions.append(description)
    print(f"{i}/{total}")
    time.sleep(0.05)

df = df.with_columns(pl.Series("Description", descriptions))

1/391
2/391
3/391
4/391
5/391
6/391
7/391
8/391
9/391
10/391
11/391
12/391
13/391
14/391
15/391
16/391
17/391
18/391
19/391
20/391
21/391
22/391
23/391
24/391
25/391
26/391
27/391
28/391
29/391
30/391
31/391
32/391
33/391
34/391
35/391
36/391
37/391
38/391
39/391
40/391
41/391
42/391
43/391
44/391
45/391
46/391
47/391
48/391
49/391
50/391
51/391
52/391
53/391
54/391
55/391
56/391
57/391
58/391
59/391
60/391
61/391
62/391
63/391
64/391
65/391
66/391
67/391
68/391
69/391
70/391
71/391
72/391
73/391
74/391
75/391
76/391
77/391
78/391
79/391
80/391
81/391
82/391
83/391
84/391
85/391
86/391
87/391
88/391
89/391
90/391
91/391
92/391
93/391
94/391
95/391
96/391
97/391
98/391
99/391
100/391
101/391
102/391
103/391
104/391
105/391
106/391
107/391
108/391
109/391
110/391
111/391
112/391
113/391
114/391
115/391
116/391
117/391
118/391
119/391
120/391
121/391
122/391
123/391
124/391
125/391
126/391
127/391
128/391
129/391
130/391
131/391
132/391
133/391
134/391
135/391
136/391
137/391
138/391
139/391
140/391
141/391
142/391
143/391
144/391
145/391
146/391
147/391
148/391
149/391
150/391
151/391
152/391
153/391
154/391
155/391
156/391
157/391
158/391
159/391
160/391
161/391
162/391
163/391
164/391
165/391
166/391
167/391
168/391
169/391
170/391
171/391
172/391
173/391
174/391
175/391
176/391
177/391
178/391
179/391
180/391
181/391
182/391
183/391
184/391
185/391
186/391
187/391
188/391
189/391
190/391
191/391
192/391
193/391
194/391
195/391
196/391
197/391
198/391
199/391
200/391
201/391
202/391
203/391
204/391
205/391
206/391
207/391
208/391
209/391
210/391
211/391
212/391
213/391
214/391
215/391
216/391
217/391
218/391
219/391
220/391
221/391
222/391
223/391
224/391
225/391
226/391
227/391
228/391
229/391
230/391
231/391
232/391
233/391
234/391
235/391
236/391
237/391
238/391
239/391
240/391
241/391
242/391
243/391
244/391
245/391
246/391
247/391
248/391
249/391
250/391
251/391
252/391
253/391
254/391
255/391
256/391
257/391
258/391
259/391
260/391
261/391
262/391
263/391
264/391
265/391
266/391
267/391
268/391
269/391
270/391
271/391
272/391
273/391
274/391
275/391
276/391
277/391
278/391
279/391
280/391
281/391
282/391
283/391
284/391
285/391
286/391
287/391
288/391
289/391
290/391
291/391
292/391
293/391
294/391
295/391
296/391
297/391
298/391
299/391
300/391
301/391
302/391
303/391
304/391
305/391
306/391
307/391
308/391
309/391
310/391
311/391
312/391
313/391
314/391
315/391
316/391
317/391
318/391
319/391
320/391
321/391
322/391
323/391
324/391
325/391
326/391
327/391
328/391
329/391
330/391
331/391
332/391
333/391
334/391
335/391
336/391
337/391
338/391
339/391
340/391
341/391
342/391
343/391
344/391
345/391
346/391
347/391
348/391
349/391
350/391
351/391
352/391
353/391
354/391
355/391
356/391
357/391
358/391
359/391
360/391
361/391
362/391
363/391
364/391
365/391
366/391
367/391
368/391
369/391
370/391
371/391
372/391
373/391
374/391
375/391
376/391
377/391
378/391
379/391
380/391
381/391
382/391
383/391
384/391
385/391
386/391
387/391
388/391
389/391
390/391
391/391

In [31]:
image_urls = []
links = df["Detailed Description Link"]
total = len(links)

for i, link in enumerate(links, start=1):
    try:
        response = requests.get(link, headers=HEADERS, timeout=10)
        response.raise_for_status()
        sel = Selector(text=response.text)
        image_url = sel.css("img.attachment-post-thumbnail.size-post-thumbnail.wp-post-image::attr(src)").get()
    except Exception as e:
        print(f"[{i}/{total}] Failed {link}: {e}")
        image_url = None

    image_urls.append(image_url)
    print(f"{i}/{total}")
    time.sleep(0.05)

df = df.with_columns(pl.Series("Image URL", image_urls))

1/391
2/391
3/391
4/391
5/391
6/391
7/391
8/391
9/391
10/391
11/391
12/391
13/391
14/391
15/391
16/391
17/391
18/391
19/391
20/391
21/391
22/391
23/391
24/391
25/391
26/391
27/391
28/391
29/391
30/391
31/391
32/391
33/391
34/391
35/391
36/391
37/391
38/391
39/391
40/391
41/391
42/391
43/391
44/391
45/391
46/391
47/391
48/391
49/391
50/391
51/391
52/391
53/391
54/391
55/391
56/391
57/391
58/391
59/391
60/391
61/391
62/391
63/391
64/391
65/391
66/391
67/391
68/391
69/391
70/391
71/391
72/391
73/391
74/391
75/391
76/391
77/391
78/391
79/391
80/391
81/391
82/391
83/391
84/391
85/391
86/391
87/391
88/391
89/391
90/391
91/391
92/391
93/391
94/391
95/391
96/391
97/391
98/391
99/391
100/391
101/391
102/391
103/391
104/391
105/391
106/391
107/391
108/391
109/391
110/391
111/391
112/391
113/391
114/391
115/391
116/391
117/391
118/391
119/391
120/391
121/391
122/391
123/391
124/391
125/391
126/391
127/391
128/391
129/391
130/391
131/391
132/391
133/391
134/391
135/391
136/391
137/391
138/391
139/391
140/391
141/391
142/391
143/391
144/391
145/391
146/391
147/391
148/391
149/391
150/391
151/391
152/391
153/391
154/391
155/391
156/391
157/391
158/391
159/391
160/391
161/391
162/391
163/391
164/391
165/391
166/391
167/391
168/391
169/391
170/391
171/391
172/391
173/391
174/391
175/391
176/391
177/391
178/391
179/391
180/391
181/391
182/391
183/391
184/391
185/391
186/391
187/391
188/391
189/391
190/391
191/391
192/391
193/391
194/391
195/391
196/391
197/391
198/391
199/391
200/391
201/391
202/391
203/391
204/391
205/391
206/391
207/391
208/391
209/391
210/391
211/391
212/391
213/391
214/391
215/391
216/391
217/391
218/391
219/391
220/391
221/391
222/391
223/391
224/391
225/391
226/391
227/391
228/391
229/391
230/391
231/391
232/391
233/391
234/391
235/391
236/391
237/391
238/391
239/391
240/391
241/391
242/391
243/391
244/391
245/391
246/391
247/391
248/391
249/391
250/391
251/391
252/391
253/391
254/391
255/391
256/391
257/391
258/391
259/391
260/391
261/391
262/391
263/391
264/391
265/391
266/391
267/391
268/391
269/391
270/391
271/391
272/391
273/391
274/391
275/391
276/391
277/391
278/391
279/391
280/391
281/391
282/391
283/391
284/391
285/391
286/391
287/391
288/391
289/391
290/391
291/391
292/391
293/391
294/391
295/391
296/391
297/391
298/391
299/391
300/391
301/391
302/391
303/391
304/391
305/391
306/391
307/391
308/391
309/391
310/391
311/391
312/391
313/391
314/391
315/391
316/391
317/391
318/391
319/391
320/391
321/391
322/391
323/391
324/391
325/391
326/391
327/391
328/391
329/391
330/391
331/391
332/391
333/391
334/391
335/391
336/391
337/391
338/391
339/391
340/391
341/391
342/391
343/391
344/391
345/391
346/391
347/391
348/391
349/391
350/391
351/391
352/391
353/391
354/391
355/391
356/391
357/391
358/391
359/391
360/391
361/391
362/391
363/391
364/391
365/391
366/391
367/391
368/391
369/391
370/391
371/391
372/391
373/391
374/391
375/391
376/391
377/391
378/391
379/391
380/391
381/391
382/391
383/391
384/391
385/391
386/391
387/391
388/391
389/391
390/391
391/391

In [40]:
df.describe()

shape: (9, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ Breed     ┆ Detailed  ┆ Dog Size  ┆ … ┆ Exercise  ┆ Potential ┆ Descripti ┆ Image    │
│ ---       ┆ Name      ┆ Descripti ┆ ---       ┆   ┆ Needs     ┆ For Playf ┆ on        ┆ URL      │
│ str       ┆ ---       ┆ on Link   ┆ str       ┆   ┆ ---       ┆ ulness    ┆ ---       ┆ ---      │
│           ┆ str       ┆ ---       ┆           ┆   ┆ f64       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 391       ┆ 391       ┆ 391       ┆ … ┆ 391.0     ┆ 391.0     ┆ 391       ┆ 391      │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.982097  ┆ 4.268542  ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.943092  ┆ 0.814615  ┆ null      ┆ null     │
│ min       ┆ Afador    ┆ https://d ┆ Large     ┆ … ┆ 1.0       ┆ 1.0       ┆           ┆ https:// │
│           ┆           ┆ ogtime.co ┆           ┆   ┆           ┆           ┆           ┆ dogtime. │
│           ┆           ┆ m/dog-bre ┆           ┆   ┆           ┆           ┆           ┆ com/wp-c │
│           ┆           ┆ eds…      ┆           ┆   ┆           ┆           ┆           ┆ ontent…  │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.0       ┆ 4.0       ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 4.0       ┆ 4.0       ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 5.0       ┆ 5.0       ┆ null      ┆ null     │
│ max       ┆ Yorkshire ┆ https://d ┆ Very      ┆ … ┆ 5.0       ┆ 5.0       ┆ With a    ┆ https:// │
│           ┆ Terrier   ┆ ogtime.co ┆ Small     ┆   ┆           ┆           ┆ striking  ┆ dogtime. │
│           ┆           ┆ m/dog-bre ┆           ┆   ┆           ┆           ┆ wolf-like ┆ com/wp-c │
│           ┆           ┆ eds…      ┆           ┆   ┆           ┆           ┆ app…      ┆ ontent…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [29]:
df.with_columns(
    pl.col("Description").str.strip_chars('"')
)

shape: (391, 42)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Breed     ┆ Detailed  ┆ Dog Size  ┆ Dog Breed ┆ … ┆ Intensity ┆ Exercise  ┆ Potential ┆ Descript │
│ Name      ┆ Descripti ┆ ---       ┆ Group     ┆   ┆ ---       ┆ Needs     ┆ For Playf ┆ ion      │
│ ---       ┆ on Link   ┆ str       ┆ ---       ┆   ┆ i64       ┆ ---       ┆ ulness    ┆ ---      │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆           ┆ i64       ┆ ---       ┆ str      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Afador    ┆ https://d ┆ Very      ┆ Mixed     ┆ … ┆ 4         ┆ 4         ┆ 3         ┆ The      │
│           ┆ ogtime.co ┆ Large     ┆ Breed     ┆   ┆           ┆           ┆           ┆ Afador   │
│           ┆ m/dog-bre ┆           ┆ Dogs      ┆   ┆           ┆           ┆           ┆ is a     │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ cross    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ between  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ Affenhuah ┆ https://d ┆ Small     ┆ Mixed     ┆ … ┆ 3         ┆ 3         ┆ 3         ┆ The Affe │
│ ua        ┆ ogtime.co ┆           ┆ Breed     ┆   ┆           ┆           ┆           ┆ nhuahua  │
│           ┆ m/dog-bre ┆           ┆ Dogs      ┆   ┆           ┆           ┆           ┆ is a     │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ mixed    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bre…     │
│ Affenpins ┆ https://d ┆ Small     ┆ Companion ┆ … ┆ 3         ┆ 3         ┆ 4         ┆ The Affe │
│ cher      ┆ ogtime.co ┆           ┆ Dogs      ┆   ┆           ┆           ┆           ┆ npinsche │
│           ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ r is a   │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ small t… │
│ Afghan    ┆ https://d ┆ Very      ┆ Hound     ┆ … ┆ 2         ┆ 4         ┆ 4         ┆ The      │
│ Hound     ┆ ogtime.co ┆ Large     ┆ Dogs      ┆   ┆           ┆           ┆           ┆ Afghan   │
│           ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ Hound is │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ a medium │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -t…      │
│ Airedale  ┆ https://d ┆ Very      ┆ Terrier   ┆ … ┆ 3         ┆ 5         ┆ 5         ┆ The      │
│ Terrier   ┆ ogtime.co ┆ Large     ┆ Dogs      ┆   ┆           ┆           ┆           ┆ Airedale │
│           ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ Terrier, │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ commonly │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Wirehaire ┆ https://d ┆ Very      ┆ Sporting  ┆ … ┆ 3         ┆ 4         ┆ 5         ┆ The Wire │
│ d         ┆ ogtime.co ┆ Large     ┆ Dogs      ┆   ┆           ┆           ┆           ┆ haired   │
│ Pointing  ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ Pointing │
│ Griffon   ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ Griffo…  │
│ Xoloitzcu ┆ https://d ┆ Large     ┆ Companion ┆ … ┆ 3         ┆ 3         ┆ 3         ┆ The Xolo │
│ intli     ┆ ogtime.co ┆           ┆ Dogs      ┆   ┆           ┆           ┆           ┆ itzcuint │
│           ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ li, also │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ calle…   │
│ Yakutian  ┆ https://d ┆ Very      ┆ Working   ┆ … ┆ 3         ┆ 5         ┆ 4         ┆ The      │
│ Laika     ┆ ogtime.co ┆ Large     ┆ Dogs      ┆   ┆           ┆           ┆           ┆ Yakutian │
│           ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ Laika is │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ an       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ancie…   │
│ Yorkipoo  ┆ https://d ┆ Small     ┆ Hybrid    ┆ … ┆ 3         ┆ 3         ┆ 4         ┆ The      │
│           ┆ ogtime.co ┆           ┆ Dogs      ┆   ┆           ┆           ┆           ┆ Yorkipoo │
│           ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ is a sma │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ ll-sized │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ Yorkshire ┆ https://d ┆ Very      ┆ Companion ┆ … ┆ 4         ┆ 4         ┆ 5         ┆ The York │
│ Terrier   ┆ ogtime.co ┆ Small     ┆ Dogs      ┆   ┆           ┆           ┆           ┆ shire    │
│           ┆ m/dog-bre ┆           ┆           ┆   ┆           ┆           ┆           ┆ Terrier, │
│           ┆ eds…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ affecti… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [36]:
df.write_csv('scraping/assets/dogs_cleaned_with_description_and_img.csv')